// @ts-check
// Single monorepo-wide ESLint (flat) config. Per-package `lint` scripts run
// `eslint .`, which discovers this file by walking up to the repo root.
import { base } from "@bookhelper/config/eslint/base";
import reactHooks from "eslint-plugin-react-hooks";
import jsxA11y from "eslint-plugin-jsx-a11y";
import globals from "globals";

export default [
  {
    ignores: [
      "**/dist/**",
      "**/.next/**",
      "**/out/**",
      "**/coverage/**",
      "**/.turbo/**",
      "**/*.config.{js,mjs,cjs,ts}",
      "packages/design-tokens/styles/**",
      // Auto-generated by Next.js ("should not be edited") and uses a
      // path triple-slash reference our rules otherwise forbid.
      "**/next-env.d.ts",
    ],
  },
  ...base,
  // NestJS uses emitted decorator metadata, which requires class symbols to be
  // VALUE imports even when only referenced as constructor parameter types.
  // Disable `consistent-type-imports` across the core-api package to avoid
  // breaking DI just to satisfy a stylistic rule.
  {
    files: ["apps/core-api/**/*.ts"],
    rules: {
      "@typescript-eslint/consistent-type-imports": "off",
    },
  },
  // React + accessibility rules, scoped to the web app and the React UI
  // packages (shared primitives + the Reader shell UI).
  {
    files: [
      "apps/web/**/*.{ts,tsx,jsx}",
      "packages/ui/**/*.{ts,tsx,jsx}",
      "packages/reader-ui/**/*.{ts,tsx,jsx}",
    ],
    plugins: { "react-hooks": reactHooks, "jsx-a11y": jsxA11y },
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,
    },
  },
];
