/**
 * Integration + contract tests for the PDF adapter.
 *
 * These run against real PDF bytes generated by `pdf-lib` at test time
 * (no checked-in binaries). They cover the *adapter contract* end-to-end:
 *
 *   • The factory satisfies `DocumentAdapter` (compile-time check via
 *     the variable typing below; runtime tests verify behavior).
 *   • Opening produces a manifest with the expected metadata.
 *   • Capabilities reflect the document.
 *   • Navigation steps respect document bounds.
 *   • Text extraction round-trips real text.
 *   • Image enumeration returns descriptors.
 *   • Close() is idempotent and drops resources.
 *   • Edge cases: corrupt PDF, empty PDF, missing metadata, page-range bounds.
 *
 * pdfjs-dist is genuinely loaded — these are slower than the unit tests
 * but still well under the per-test budget set in vitest.config.ts.
 */

import { describe, expect, it } from "vitest";
import { AdapterError, type DocumentAdapter } from "@bookhelper/reader-core";
import { createPdfAdapter, type PdfDocumentSession } from "./adapter.js";
import { buildPdfFixture } from "./test-helpers.js";

async function openWithBytes(
  bytes: Uint8Array,
  overrides: { docId?: string; password?: string } = {},
): Promise<{ adapter: DocumentAdapter; session: PdfDocumentSession }> {
  const adapter = createPdfAdapter({
    dataSource: async () => bytes,
    ...(overrides.password ? { password: overrides.password } : {}),
    capabilityProbePages: 2,
  });
  const session = (await adapter.open({
    docId: overrides.docId ?? "test-doc",
  })) as PdfDocumentSession;
  return { adapter, session };
}

describe("createPdfAdapter — open()", () => {
  it("opens a normal PDF and publishes a complete manifest", async () => {
    const bytes = await buildPdfFixture({
      title: "Adapter Smoke",
      author: "QA",
      producer: "pdf-lib",
      language: "en",
      pageTexts: ["Hello World", "Second page", "Third page"],
    });
    const { session } = await openWithBytes(bytes);
    try {
      expect(session.manifest.format).toBe("pdf");
      expect(session.manifest.title).toBe("Adapter Smoke");
      expect(session.manifest.pageCount).toBe(3);
      expect(session.manifest.blockCount).toBe(3);
      expect(session.manifest.meta.pdf.author).toBe("QA");
      expect(session.manifest.meta.pdf.producer).toContain("pdf-lib");
    } finally {
      await session.close();
    }
  });

  it("reports selection / search capabilities when text is present", async () => {
    const bytes = await buildPdfFixture({ pageTexts: ["A few words"] });
    const { session } = await openWithBytes(bytes);
    try {
      expect(session.capabilities.selection).toBe(true);
      expect(session.capabilities.search).toBe(true);
      expect(session.capabilities.tts).toBe(true);
    } finally {
      await session.close();
    }
  });

  it("reports `selection: false` for a PDF without any text layer", async () => {
    const bytes = await buildPdfFixture({ pageCount: 1 }); // no pageTexts
    const { session } = await openWithBytes(bytes);
    try {
      expect(session.capabilities.selection).toBe(false);
      expect(session.capabilities.search).toBe(false);
    } finally {
      await session.close();
    }
  });

  it("maps corrupt input to E_PDF_INVALID", async () => {
    const bytes = new Uint8Array([0, 1, 2, 3, 4, 5, 6, 7]);
    const adapter = createPdfAdapter({ dataSource: async () => bytes });
    await expect(adapter.open({ docId: "broken" })).rejects.toMatchObject({
      code: "E_PDF_INVALID",
    });
  });

  it("close() is idempotent", async () => {
    const bytes = await buildPdfFixture({ pageTexts: ["x"] });
    const { session } = await openWithBytes(bytes);
    await session.close();
    await session.close(); // should not throw
    expect(session.manifest.pageCount).toBe(1);
  });
});

describe("createPdfAdapter — navigation", () => {
  it("steps page-by-page and respects boundaries", async () => {
    const bytes = await buildPdfFixture({ pageTexts: ["a", "b", "c"] });
    const { session } = await openWithBytes(bytes);
    try {
      const nav = session.navigation;
      const first = {
        kind: "point" as const,
        position: { blockId: "page:1", offset: 0, globalOffset: 0, docVersion: 1 },
      };
      const next = await nav.step({ anchor: first, grain: "page", direction: "forward" });
      expect(next && "target" in next ? next.target.position.blockId : null).toBe("page:2");
      const tooFar = await nav.step({
        anchor: {
          kind: "point",
          position: { blockId: "page:3", offset: 0, globalOffset: 0, docVersion: 1 },
        },
        grain: "page",
        direction: "forward",
      });
      expect(tooFar).toBeNull();
    } finally {
      await session.close();
    }
  });
});

describe("createPdfAdapter — text extraction", () => {
  it("round-trips the text written by pdf-lib", async () => {
    const bytes = await buildPdfFixture({ pageTexts: ["Hello Reader Core"] });
    const { session } = await openWithBytes(bytes);
    try {
      const text = await session.extractPageText(1);
      expect(text.text.toLowerCase()).toContain("hello");
      expect(text.text.toLowerCase()).toContain("reader");
    } finally {
      await session.close();
    }
  });

  it("streams pages in order", async () => {
    const bytes = await buildPdfFixture({ pageTexts: ["A", "B", "C"] });
    const { session } = await openWithBytes(bytes);
    try {
      const pages: number[] = [];
      for await (const page of session.streamText()) {
        pages.push(page.page);
      }
      expect(pages).toEqual([1, 2, 3]);
    } finally {
      await session.close();
    }
  });

  it("rejects out-of-range page numbers", async () => {
    const bytes = await buildPdfFixture({ pageTexts: ["x"] });
    const { session } = await openWithBytes(bytes);
    try {
      await expect(session.extractPageText(0)).rejects.toMatchObject({ code: "E_READER_ADAPTER" });
      await expect(session.extractPageText(99)).rejects.toMatchObject({ code: "E_READER_ADAPTER" });
    } finally {
      await session.close();
    }
  });

  it("rejects operations after close", async () => {
    const bytes = await buildPdfFixture({ pageTexts: ["x"] });
    const { session } = await openWithBytes(bytes);
    await session.close();
    await expect(session.extractPageText(1)).rejects.toThrow();
  });
});

describe("createPdfAdapter — capability contract", () => {
  it("satisfies DocumentAdapter at the type level", () => {
    const adapter: DocumentAdapter = createPdfAdapter({ dataSource: async () => new Uint8Array() });
    expect(adapter.name).toBe("pdf");
  });

  it("uses the bytes returned by the data source for the given docId", async () => {
    const bytes = await buildPdfFixture({ pageTexts: ["hi"], title: "Bound" });
    let lastDocId: string | null = null;
    const adapter = createPdfAdapter({
      dataSource: async ({ docId }) => {
        lastDocId = docId;
        return bytes;
      },
    });
    const session = (await adapter.open({ docId: "doc-XYZ" })) as PdfDocumentSession;
    try {
      expect(lastDocId).toBe("doc-XYZ");
      expect(session.manifest.title).toBe("Bound");
    } finally {
      await session.close();
    }
  });

  it("surfaces non-pdf-blockId locators as adapter errors", async () => {
    const bytes = await buildPdfFixture({ pageTexts: ["x"] });
    const { session } = await openWithBytes(bytes);
    try {
      await expect(
        session.resolveLocator({
          kind: "point",
          position: { blockId: "epub:cfi", offset: 0, globalOffset: 0, docVersion: 1 },
        }),
      ).rejects.toBeInstanceOf(AdapterError);
    } finally {
      await session.close();
    }
  });
});

describe("createPdfAdapter — performance / large docs", () => {
  it("lazyOffsetTable opens fast (skips per-page scan) and still resolves locators", async () => {
    const bytes = await buildPdfFixture({
      pageCount: 50,
      pageTexts: new Array(50).fill("page text"),
    });
    const adapter = createPdfAdapter({
      dataSource: async () => bytes,
      lazyOffsetTable: true,
      capabilityProbePages: 1,
    });
    const session = (await adapter.open({ docId: "fifty" })) as PdfDocumentSession;
    try {
      expect(session.manifest.pageCount).toBe(50);
      // With lazy table, totalChars is 0 (deferred), but navigation still works.
      const res = await session.navigation.step({
        anchor: {
          kind: "point",
          position: { blockId: "page:25", offset: 0, globalOffset: 0, docVersion: 1 },
        },
        grain: "page",
        direction: "forward",
      });
      expect(res && "target" in res ? res.target.position.blockId : null).toBe("page:26");
    } finally {
      await session.close();
    }
  });
});
